plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '0.1.0'
group = 'com.akitaattribute.biomepockets'

base {
    archivesName = 'biomepockets'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.18.2'
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            mods {
                biomepockets {
                    source sourceSets.main
                }
            }
        }

        client { }
        server { args '--nogui' }
    }
}

repositories { }

dependencies {
    minecraft 'net.minecraftforge:forge:1.18.2-40.3.12'
}

tasks.named('processResources', ProcessResources).configure {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
